# Form implementation generated from reading ui file 'edit_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditWindow(object):
    def setupUi(self, EditWindow):
        EditWindow.setObjectName("EditWindow")
        EditWindow.resize(900, 700)
        self.mainLayout = QtWidgets.QVBoxLayout(EditWindow)
        self.mainLayout.setObjectName("mainLayout")
        self.toolbar = QtWidgets.QToolBar(parent=EditWindow)
        self.toolbar.setObjectName("toolbar")
        self.mainLayout.addWidget(self.toolbar)
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.mainLayout.addLayout(self.searchLayout)
        self.findReplaceLayout = QtWidgets.QHBoxLayout()
        self.findReplaceLayout.setObjectName("findReplaceLayout")
        self.findLabel = QtWidgets.QLabel(parent=EditWindow)
        self.findLabel.setObjectName("findLabel")
        self.findReplaceLayout.addWidget(self.findLabel)
        self.findField = QtWidgets.QLineEdit(parent=EditWindow)
        self.findField.setObjectName("findField")
        self.findReplaceLayout.addWidget(self.findField)
        self.replaceLabel = QtWidgets.QLabel(parent=EditWindow)
        self.replaceLabel.setObjectName("replaceLabel")
        self.findReplaceLayout.addWidget(self.replaceLabel)
        self.replaceField = QtWidgets.QLineEdit(parent=EditWindow)
        self.replaceField.setObjectName("replaceField")
        self.findReplaceLayout.addWidget(self.replaceField)
        self.replaceButton = QtWidgets.QPushButton(parent=EditWindow)
        self.replaceButton.setObjectName("replaceButton")
        self.findReplaceLayout.addWidget(self.replaceButton)
        self.mainLayout.addLayout(self.findReplaceLayout)
        self.splitter = QtWidgets.QSplitter(parent=EditWindow)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableView = QtWidgets.QTableView(parent=self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setGridStyle(QtCore.Qt.PenStyle.DotLine)
        self.tableView.setObjectName("tableView")
        self.mainLayout.addWidget(self.splitter)
        self.statusBar = QtWidgets.QStatusBar(parent=EditWindow)
        self.statusBar.setObjectName("statusBar")
        self.mainLayout.addWidget(self.statusBar)

        self.retranslateUi(EditWindow)
        QtCore.QMetaObject.connectSlotsByName(EditWindow)

    def retranslateUi(self, EditWindow):
        _translate = QtCore.QCoreApplication.translate
        EditWindow.setWindowTitle(_translate("EditWindow", "Uredi Excel podatke"))
        self.findLabel.setText(_translate("EditWindow", "Pronađi:"))
        self.replaceLabel.setText(_translate("EditWindow", "Zamijeni sa:"))
        self.replaceButton.setText(_translate("EditWindow", "Zamijeni"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditWindow = QtWidgets.QDialog()
    ui = Ui_EditWindow()
    ui.setupUi(EditWindow)
    EditWindow.show()
    sys.exit(app.exec())
